#!/usr/bin/env node
/**
 * OPA Policy Registry Server
 *
 * Single server that handles:
 * - Static file serving for the React frontend
 * - Runtime configuration via command line flags
 *
 * Zero external dependencies - uses only Node.js built-ins.
 *
 * Usage:
 *   node serve.cjs --api-url http://localhost:8181/api --port 3000
 *
 * Options:
 *   --api-url, -a   Backend API base URL (default: /api)
 *   --port, -p      Port to serve on (default: 3000)
 *   --help, -h      Show help
 */

const http = require('http');
const https = require('https');
const fs = require('fs');
const path = require('path');

/**
 * Proxy POST requests to GitHub API (bypasses CORS)
 */
function proxyToGitHub(githubPath, req, res) {
  let body = '';
  req.on('data', chunk => { body += chunk; });
  req.on('end', () => {
    const options = {
      hostname: 'github.com',
      port: 443,
      path: githubPath,
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
        'Content-Length': Buffer.byteLength(body),
      },
    };

    const proxyReq = https.request(options, (proxyRes) => {
      let data = '';
      proxyRes.on('data', chunk => { data += chunk; });
      proxyRes.on('end', () => {
        res.writeHead(proxyRes.statusCode, {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*',
        });
        res.end(data);
      });
    });

    proxyReq.on('error', (err) => {
      console.error('GitHub proxy error:', err);
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'Proxy error', message: err.message }));
    });

    proxyReq.write(body);
    proxyReq.end();
  });
}

// Parse command line arguments
function parseArgs() {
  const args = process.argv.slice(2);
  const config = {
    apiUrl: process.env.API_BASE_URL || '/api',
    port: parseInt(process.env.PORT, 10) || 3000,
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    const next = args[i + 1];

    if (arg === '--help' || arg === '-h') {
      console.log(`
OPA Policy Registry Server

Usage:
  node serve.cjs [options]

Options:
  --api-url, -a <url>   Backend API base URL (default: /api)
  --port, -p <port>     Port to serve on (default: 3000)

Environment Variables:
  API_BASE_URL          Same as --api-url
  PORT                  Same as --port

Examples:
  node serve.cjs --api-url http://localhost:8181/api
  node serve.cjs -a http://backend:8181/api -p 8080
`);
      process.exit(0);
    }

    if (arg === '--api-url' || arg === '-a') {
      config.apiUrl = next;
      i++;
    } else if (arg === '--port' || arg === '-p') {
      config.port = parseInt(next, 10);
      i++;
    }
  }

  return config;
}

// MIME types for static files
const mimeTypes = {
  '.html': 'text/html',
  '.js': 'application/javascript',
  '.css': 'text/css',
  '.json': 'application/json',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.eot': 'application/vnd.ms-fontobject',
};

function getMimeType(filePath) {
  const ext = path.extname(filePath).toLowerCase();
  return mimeTypes[ext] || 'application/octet-stream';
}

function main() {
  const config = parseArgs();
  const buildPath = path.join(__dirname, 'build');

  // Check if build folder exists
  if (!fs.existsSync(buildPath)) {
    console.error('Error: build/ folder not found. Run "npm run build" first.');
    process.exit(1);
  }

  // Generate runtime config
  const runtimeConfig = `// Runtime configuration - generated by serve.cjs
window.__RUNTIME_CONFIG__ = ${JSON.stringify({ API_BASE_URL: config.apiUrl }, null, 2)};
`;

  const server = http.createServer((req, res) => {
    const urlPath = req.url.split('?')[0];

    // Handle CORS preflight for GitHub proxy endpoints
    if (req.method === 'OPTIONS' && urlPath.startsWith('/auth/github/')) {
      res.writeHead(204, {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'POST, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type',
      });
      res.end();
      return;
    }

    // GitHub Device Flow proxy: request device code
    if (req.method === 'POST' && urlPath === '/auth/github/device/code') {
      proxyToGitHub('/login/device/code', req, res);
      return;
    }

    // GitHub Device Flow proxy: poll for access token
    if (req.method === 'POST' && urlPath === '/auth/github/oauth/access_token') {
      proxyToGitHub('/login/oauth/access_token', req, res);
      return;
    }

    // Health check endpoint
    if (urlPath === '/api/health') {
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ status: 'ok', apiUrl: config.apiUrl }));
      return;
    }

    // Serve dynamic config.js with runtime values
    if (urlPath === '/config.js') {
      res.writeHead(200, { 'Content-Type': 'application/javascript' });
      res.end(runtimeConfig);
      return;
    }

    // Static file serving
    let filePath = path.join(buildPath, urlPath);

    // Default to index.html for SPA routing
    if (urlPath === '/' || !fs.existsSync(filePath) || fs.statSync(filePath).isDirectory()) {
      const hasExtension = path.extname(urlPath) !== '';
      if (!hasExtension || urlPath === '/') {
        filePath = path.join(buildPath, 'index.html');
      }
    }

    // Serve file
    fs.readFile(filePath, (err, data) => {
      if (err) {
        res.writeHead(404);
        res.end('Not Found');
        return;
      }

      const mimeType = getMimeType(filePath);
      res.writeHead(200, { 'Content-Type': mimeType });
      res.end(data);
    });
  });

  server.listen(config.port, () => {
    console.log(`
┌──────────────────────────────────────────────────────────────┐
│  OPA Policy Registry                                         │
├──────────────────────────────────────────────────────────────┤
│  Server:   http://localhost:${String(config.port).padEnd(31)}│
│  API URL:  ${config.apiUrl.padEnd(49)}│
└──────────────────────────────────────────────────────────────┘
`);
  });
}

main();
